# Generated by Django 4.2.1 on 2023-06-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('studentId', models.AutoField(default='', primary_key=True, serialize=False)),
                ('stdName', models.CharField(max_length=100)),
                ('result', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ranking', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('stdName', models.CharField(default='', max_length=100)),
                ('averageScore', models.IntegerField()),
                ('achievement', models.IntegerField()),
                ('skillCertificate', models.IntegerField()),
                ('testResult', models.IntegerField()),
                ('schoolName', models.CharField(default='', max_length=100)),
                ('schoolAccreditation', models.IntegerField()),
            ],
        ),
    ]
