# Generated by Django 4.2.1 on 2023-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_result_admissionresult_admsresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='c1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='c2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='c3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='c4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='c5',
            field=models.CharField(default='', max_length=100),
        ),
    ]
