# Generated by Django 4.2.1 on 2023-06-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_admissionresult_c1_admissionresult_c2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionresult',
            name='admsResult',
        ),
    ]
