# Generated by Django 4.2.1 on 2023-06-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_admissionresult_admsresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='achievement',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='averageScore',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='FirstName',
            new_name='schoolAccreditation',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='LastName',
            new_name='skillCertificate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='RegistrationNo',
            new_name='testResult',
        ),
    ]
