# Generated by Django 4.2.1 on 2023-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rename_course_student_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schoolName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stdName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
