# Generated by Django 4.2.1 on 2023-05-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportScore', models.CharField(max_length=50)),
                ('achievement', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('interview', models.CharField(max_length=50)),
                ('SchoolAcc', models.CharField(max_length=50)),
            ],
        ),
    ]
